### PR TITLE
Updated tree.txt

### PR DESCRIPTION
**Pull request by r4gesingh47**
Added new directories and files

### CODE REVIEW

**Comment by bacloud14** [comment]
Thank you for your contribution @r4gesingh47 
I need to check this later though. The purpose is to show all files including those ignored by Git. Like /creds/ and so.

**Comment by bacloud14** [comment]
Could you add the command as part of the build process by the way? 
Thanks 😊

**Comment by r4gesingh47** [comment]
can you guide me on where i am unable to find the config file

**Comment by bacloud14** [comment]
Yes and that would be part of build process. Check webpack config file in client folder

**Comment by r4gesingh47** [comment]
Sorry this is my first time with webpack config so i am confused and unable to understand i used tree command in linux to generate the tree of the repo first i was doing it manually tho.

**Comment by bacloud14** [comment]
Sorry but closing this for now.

**Pull request closed without merging**
